language: java
sudo: true
dist: trusty
jdk: -oraclejdk15

nitifications:
  email:
    recipients:
      - frowzygleb@gmail.com
    on_success: never
    on_failure: always

addons:
  apt:
    packages:
      - oracle-java15-installer
before_install:
  - chmod +x mvnw